### ISSUE TITLE
Running ffcast without interactive shell.

### ISSUE THREAD

**Issue by amosbird** [lolilolicon/FFcast#22] opened 2016-11-17 11:40 UTC
Thanks for this cute tool. I'd like to bind a combo key to this command:
```
    TMP_AVI=$(mktemp /tmp/outXXXXXXXXXX.avi)
    ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
        -video_size %s -i %D+%c -codec:v huffyuv                  \
        -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $TMP_AVI        \
    && convert -set delay 10 -layers Optimize $TMP_AVI gif:- | copyq write image/gif - && rm -rf $TMP_AVI
```
And another key to stop recording.
How can I make it work?

**Comment by lolilolicon** [comment] 2016-11-17 11:52
This is a duplicate of #19. The `pkill` method should work well enough.

**Comment by amosbird** [comment] 2016-11-17 12:34
hmm, `pkill` makes it return abnormally. The subsequent commands aren't executed. Moreover, I cannot quit the selection phase by `ESC`.

**Comment by lolilolicon** [comment] 2016-11-17 15:56
Well you need to adjust your script a bit.

> The subsequent commands aren't executed.

Just don't use `&&`. Check the value of `$?` if necessary.

> I cannot quit the selection phase by `ESC`.

You could do a click without dragging, which makes ffmpeg fail and return 1.
You could also do `eval $(ffcast -s echo w=%w h=%h x=%x y=%y)` first, and then check/use `$w` etc. later.

**Closed** 2016-11-25 07:22 UTC
